version: "3.7"

services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"

  logstash:
    build: .
    container_name: logstash
    # depends_on:
    #   - elasticsearch
    ports:
      - "5044:5044" # Expose Logstash HTTP input
    # volumes:
    #   - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    volumes:
      - "/data/coolify/applications/ggc4cwo0ksc8ks00ow04cg4s/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.11.0
  #   container_name: kibana
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"
