version: "3.8"

services:
  logstash:
    build: .
    container_name: logstash
    ports:
      - "5044:5044"
    environment:
      - MONGO_URI=
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
